// reviewSummary.js — writes the new joinee's 30/60/90-day review summary and emails it to
// them, with the recruiter on cc.
//
// The summary is generated by the system from what the manager and recruiter filled in that
// review's tab of the AL_DI_HR_019 tracking sheet ("Tracking - Month -1/2/3"): tasks and
// completion, the lead's observations and suggestions, and the recruiter's notes. Gemini
// writes it as a short note to the joinee; if Gemini isn't configured or fails, a plain
// point-by-point summary of the filled-in rows is sent instead. Sent once the manager has
// replied "Confirmed" (the sheet is final at that point). The email asks the joinee to
// reply "Confirmed" / "Not Received", which closes the milestone (t45/t48/t51).

const { google } = require('googleapis');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const config = require('./config');

const MONTH_TABS = { 30: 'Tracking - Month -1', 60: 'Tracking - Month -2', 90: 'Tracking - Month -3' };

// Pure: turns the tab's rows into "label: value" lines, keeping only rows that have
// something filled in besides their label. Header-only rows (title, "Filled by Recruiter",
// "Lead's Observations ...") drop out because nothing is filled next to them.
function extractFilledRows(rows) {
  const HEADER_VALUES = new Set(['filled by recruiter', "lead's observations on the tasks assigned", 'suggestions for improvements from the lead']);
  const lines = [];
  for (const row of (rows || []).slice(1)) { // row 0 is the tab title
    const [label, ...rest] = (row || []).map(c => String(c || '').trim());
    const values = rest.filter(v => v && !HEADER_VALUES.has(v.toLowerCase()));
    if (values.length === 0) continue;
    const cleanLabel = (label || '').split('\n')[0].trim(); // first line of multi-line labels
    lines.push(cleanLabel ? `${cleanLabel}: ${values.join(' | ')}` : values.join(' | '));
  }
  return lines;
}

function plainSummary(lines) {
  return lines.map(l => `• ${l}`).join('\n');
}

async function writeSummary(employee, dayMark, lines) {
  const fallback = plainSummary(lines);
  if (!process.env.GEMINI_API_KEY) return fallback;

  const prompt = `You are an HR assistant. Below is what a new joinee's reporting manager and recruiter recorded in the joinee's ${dayMark}-day review sheet: tasks and completion, the lead's ratings (Good / Satisfactory / Bad) and observations, suggestions for improvement, and the recruiter's notes.

Write the review summary that will be emailed to the joinee. Address them directly as "you" and write on behalf of the HR team ("we"), never "I". Use a professional, encouraging and constructive tone, 4-7 sentences. Cover their progress on assigned tasks, strengths, and areas to improve with the suggestions given. Rules:
- Base it strictly on the data — do not invent details, ratings or outcomes.
- Do not make promises or commitments on the company's behalf (e.g. about requests, policies, pay or schedules).
- Do not state or predict a probation decision.
- No greeting or sign-off, just the summary body.

Joinee: ${employee.name}
Review: ${dayMark}-day

Review sheet:
${lines.join('\n')}`;

  try {
    const model = new GoogleGenerativeAI(process.env.GEMINI_API_KEY).getGenerativeModel({ model: config.geminiModel });
    const response = await model.generateContent(prompt);
    const text = response.response.text().trim();
    return text || fallback;
  } catch (err) {
    console.warn(`[ReviewSummary] Gemini summary failed for ${employee.name} (${dayMark}-day): ${err.message} — sending the plain summary`);
    return fallback;
  }
}

// Writes and sends the dayMark summary to the joinee (cc recruiter). Skips if it was
// already sent, unless opts.force (joinee replied "Not Received").
// Returns 'sent' or 'already-sent'; throws if the sheet can't be read, has nothing filled
// in, or the email can't be sent.
async function sendReviewSummaryToJoinee(auth, employee, dayMark, opts = {}) {
  const { name } = employee;
  const monthTab = MONTH_TABS[dayMark];
  if (!monthTab) throw new Error(`no review tab for day ${dayMark}`);

  employee.reviewSummarySentAt = employee.reviewSummarySentAt || {};
  if (employee.reviewSummarySentAt[dayMark] && !opts.force) {
    console.log(`[ReviewSummary] ${dayMark}-day summary already sent to ${name} on ${employee.reviewSummarySentAt[dayMark]} — skipping`);
    return 'already-sent';
  }
  if (!employee.projectIntroSheetId) throw new Error('no tracking sheet on record');

  const sheets = google.sheets({ version: 'v4', auth });
  const res = await sheets.spreadsheets.values.get({ spreadsheetId: employee.projectIntroSheetId, range: `'${monthTab}'!A1:C60` });
  const lines = extractFilledRows(res.data.values);
  if (lines.length === 0) throw new Error(`the ${monthTab} tab has nothing filled in`);

  const summary = await writeSummary(employee, dayMark, lines);
  const { sendReviewSummaryEmail } = require('./emailSender');
  await sendReviewSummaryEmail(employee, dayMark, summary);

  employee.reviewSummarySentAt[dayMark] = new Date().toISOString();
  if (employee._saveState) employee._saveState();
  console.log(`[ReviewSummary] ${dayMark}-day summary sent to ${name}${opts.force ? ' (resent)' : ''}`);
  return 'sent';
}

module.exports = { extractFilledRows, plainSummary, sendReviewSummaryToJoinee, MONTH_TABS };
